import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// src/components/Rightbar.tsx
import { useAppSelector } from '@/hooks/use-store';
import { Avatar, Box, Button, HStack, Text, VStack } from '@chakra-ui/react';
import profileBackground from '../../../assets/a.jpg'; // Pastikan path ini benar
export function Rightbar() {
    var _a = useAppSelector(function (state) { return state.auth; }), fullName = _a.fullName, email = _a.email;
    console.log("Redux state auth:", useAppSelector(function (state) { return state.auth; }));
    console.log("Full Name:", fullName);
    console.log("Email:", email);
    return (_jsxs(Box, { w: "350px" // Lebar card
        , bg: "black" // Background untuk keseluruhan Rightbar
        , boxShadow: "md", borderRadius: "md", children: [_jsxs(Box, { mb: 6, p: 3, borderRadius: "md", border: "1px solid black", bg: "#262626" // Background color untuk profil card
                , color: "white", position: "relative", overflow: "hidden" // Mengatur overflow untuk menutupi bagian avatar yang keluar dari card
                , children: [_jsx(Text, { fontSize: "md" // Mengurangi ukuran font
                        , fontWeight: "bold", color: "white", mb: 3, children: "My Profile" }), _jsx(Box, { h: "80px" // Mengecilkan ukuran background image
                        , borderRadius: "md", backgroundImage: "url(".concat(profileBackground, ")"), backgroundSize: "cover", backgroundPosition: "center", position: "relative", mb: 8, children: _jsx(Box, { position: "absolute", bottom: -15, left: 3, transform: "translateY(50%)" // Mengatur posisi avatar agar berada setengah di luar gambar
                            , children: _jsx(Avatar, { size: "lg" // Mengurangi ukuran avatar
                                , name: "User Name", src: "https://bit.ly/dan-abramov", border: "2px solid white", borderRadius: "full" }) }) }), _jsxs(HStack, { spacing: 3, mt: 3, justify: "flex-end", children: [" ", _jsx(Button, { colorScheme: "green", size: "sm", variant: "outline", borderColor: "white", color: "white", borderRadius: "full", _hover: { borderColor: 'green.400', color: 'green.400' }, children: "Edit Profile" })] }), _jsxs(VStack, { align: "start", spacing: 1, children: [_jsx(Text, { fontSize: "xl", fontWeight: "bold", children: fullName }), _jsx(Text, { fontSize: 'sm', color: '#909090', children: email }), _jsx(Text, { fontSize: "sm", color: "gray.200", children: "picked over by the worms, and weird fishes" }), _jsxs(HStack, { spacing: 3, children: [" ", _jsxs(HStack, { spacing: 1, children: [_jsx(Text, { fontSize: "sm", fontWeight: "bold", color: "white", children: "123" }), _jsx(Text, { fontSize: "sm", color: "#909090", children: "Following" })] }), _jsxs(HStack, { spacing: 1, children: [_jsx(Text, { fontSize: "sm", fontWeight: "bold", color: "white", children: "456" }), _jsx(Text, { fontSize: "sm", color: "#909090", children: "Followers" })] })] })] })] }), _jsxs(Box, { p: 4, borderRadius: "md", border: "1px solid black", bg: "#262626" // Background color untuk suggestion card
                , color: "white", mb: 6, children: [_jsx(Text, { fontSize: "lg", fontWeight: "bold", children: "Suggested for You" }), _jsx(VStack, { spacing: 1, align: "stretch", children: [1, 2, 3, 4, 5].map(function (item) { return (_jsxs(Box, { display: "flex", alignItems: "center", p: 2, borderRadius: "md", bg: "transparent", children: [_jsx(Avatar, { size: "sm", name: "User ".concat(item), src: "https://bit.ly/dan-abramov", mr: 3 }), _jsxs(VStack, { spacing: 1, align: "start", flex: "1", children: [_jsxs(Text, { fontSize: "sm", fontWeight: "bold", children: ["User ", item] }), _jsxs(Text, { fontSize: "xs", color: "gray.400", children: ["user", item, "@example.com"] })] }), _jsx(Button, { ml: "auto", size: "sm", colorScheme: "white", variant: item === 1 ? "solid" : "outline", borderColor: "white", color: item === 1 ? "white" : "white.400", borderRadius: "full", _hover: { borderColor: item === 1 ? 'white.400' : 'white', color: item === 1 ? 'white.400' : 'white' }, children: item === 1 ? "Following" : "Follow" })] }, item)); }) })] }), _jsxs(Box, { p: 1, borderRadius: "sm", border: "1px solid black", bg: "#262626" // Background color untuk credit card
                , color: "white", fontSize: "sm", textAlign: "center", children: [_jsx(Text, { children: "Developed By DWI PURNOMO" }), _jsx(Text, { children: " Powered by Dumbways Indonesia" })] })] }));
}
